language: minimal

dist: bionic

install:
  - git clone --depth=1 https://github.com/junegunn/vader.vim.git

script:
  - test/run

notifications:
  irc:
    channels:
      - "chat.freenode.net##mgedmin"
    on_success: change
    on_failure: always
    template:
      # ping my nick so I get a pushbullet notification on my phone
      - "mgedmin: %{repository_name} (%{branch}) build %{result}: %{build_url}"
